# config/routes/attributes.yaml
controllers:
  resource:
    path: ../../src/Controller/
    namespace: App\Controller
  prefix: /api/v1
  type: attribute


kernel:
  resource: App\Kernel
  type: attribute